#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os

from kvmd.apps.kvmd.table import LogTable

sqlite_path = "/etc/kvmd/sqlite.db"


def clean_log():
    if not os.path.exists(sqlite_path):
        return 0
    log_table = LogTable(sqlite_path)
    log_table.delete_log()

